site_name: An Introduction to Docker
nav:
  - Introduction: index.md
  - Containers: 01_containers.md
  - Installation: 02_installation.md
  - Docker SSH: 03_docker-ssh.md
  - Basic Commands: 04_basic-commands.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js